from typing_extensions import List, Literal
from pydantic import BaseModel, Field


class FilePlan(BaseModel):
    """
    Specific file-level instruction set for the coding agent.

    Details the path, action type, and precise instructions for modification or creation
    of a single file within the workspace.

    CONCEPT: Decouples high-level planning from low-level execution by providing scoped, 
    file-specific context to the coder, ensuring they only focus on the relevant changes.

    Attributes:
        path (str): The relative path of the target file from the work directory.
        action (Literal["create", "update"]): The type of operation to be performed.
        reason (str): Justification for why these specific changes are necessary.
        instructions (str): Precise, self-contained implementation instructions for the coder.
    """
    path: str = Field(description="This is the relative path of a file.")
    action: Literal["create", "update"]
    reason: str
    instructions: str = Field(description="""
        Precise, self-contained implementation instructions for this specific file only.
        The coder will see ONLY this field + the file content — not the global task.
        Include: what to implement, key functions/classes, inputs/outputs, 
        dependencies to import from other planned files.
    """)


class Plan(BaseModel):
    """
    High-level architectural plan consisting of multiple file-specific operations.

    Aggregates multiple FilePlan objects into a cohesive execution strategy that 
    the coding agent follows to fulfill a task.

    CONCEPT: Acts as the comprehensive roadmap for the agent, providing a summary 
     of the intended changes and a structured list of all target files.

    Attributes:
        summary (str): A high-level overview of the entire plan and its objectives.
        files (List[FilePlan]): A collection of individual file plans to be executed.
    """
    summary: str
    files: List[FilePlan]


class CodeChange(BaseModel):
    """
    Representation of a physical file change (creation or update).

    Contains the relative path and the full content of the file as it should appear 
    after the change is applied.

    CONCEPT: Encapsulates the raw output of a coding task, allowing for validation 
    and review before the changes are persisted to the filesystem.

    Attributes:
        path (str): The relative path of the file being modified or created.
        action (Literal["create", "update"]): The type of operation performed.
        content (str): The full new content of the file (Version 1 design).
    """
    path: str = Field(description="This is the relative path of file.")
    action: Literal["create", "update"]
    content: str # full new content(safe v1 design)  | In v2, you can move to diff/patch mode.


class CodeOutput(BaseModel):
    """
    Collection of all code changes generated during a single execution cycle.

    Pairs a summary of the work performed with the complete list of individual 
    code changes that were generated by the agent.

    CONCEPT: Provides a structured and unified response format for multi-file 
    coding operations, facilitating easier tracking and persistence of changes.

    Attributes:
        summary (str): A brief description of the changes made across all files.
        changes (List[CodeChange]): The list of individual code changes generated.
    """
    summary: str
    changes: List[CodeChange]


class SingleFileOutput(BaseModel):
    """
    Output structure specifically for tasks targeting a single file.

    Used when only one file is being modified or created, providing a simplified 
    version of the standard CodeOutput.

    CONCEPT: Streamlines the response format for single-target operations where 
    the complexity of a multi-file list is unnecessary.

    Attributes:
        summary (str): A brief description of the change made to the file.
        change (CodeChange): The specific code change object for the file.
    """
    summary: str
    change: CodeChange


class ReviewResult(BaseModel):
    """
    Formal evaluation of a code change by a reviewer agent.

    Indicates whether the changes are approved or need revision, listing specific 
    issues, suggestions, and a confidence score.

    CONCEPT: Provides a critical feedback loop in the agent workflow, ensuring 
    code quality and adherence to requirements through automated, iterative review.

    Attributes:
        status (Literal["approved", "needs_revision"]): The final verdict of the review.
        issues (List[str]): A list of identified problems or missing requirements.
        suggestion (List[str]): Recommendations for improving the code or fixing issues.
        confidence (float): A score between 0.0 and 1.0 representing review certainty.
    """
    status: Literal["approved", "needs_revision"]
    issues: List[str]
    suggestion: List[str]
    confidence: float = Field(description="The value must be between 0.0 - 1.0")
